#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidIME.Resource", IsApplication=true)]

namespace AndroidIME
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidLib.Resource.String.ApplicationName = global::AndroidIME.Resource.String.ApplicationName;
			global::AndroidLib.Resource.String.Hello = global::AndroidIME.Resource.String.Hello;
			global::AndroidTTR.Resource.String.ApplicationName = global::AndroidIME.Resource.String.ApplicationName;
			global::AndroidTTR.Resource.String.Hello = global::AndroidIME.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int buttonLayout = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int editText = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int inputView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int m_table_menu = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int mainLayout = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int openIMESelection = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int toggleView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ttrView = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Input = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int general_category = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int ime_name = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int label_go_key = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int label_next_key = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int label_send_key = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int label_subtype_en_GB = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int label_subtype_generic = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int language_selection_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int select_language = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int settings_name = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int word_separators = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int method = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
